// listings.js
const listings = [
  {
    id: 1,
    title: 'Cozy Apartment',
    type: 'Entire apartment',
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    price: 100,
    category: 'Luxury',
    location: 'New York',
    image: 'https://th.bing.com/th/id/OIP.Rv5BkyJ19WG-LIaiWyzujgHaE8?w=301&h=200&c=7&r=0&o=5&pid=1.7',
    description:
      'A charming and cozy apartment located in the bustling heart of New York City. This fully furnished apartment features a modern interior design, complete with a well-equipped kitchen, comfortable living space, and breathtaking views of the city skyline. It’s perfect for a family or a small group of friends looking to explore the Big Apple. Attractions such as Central Park, Times Square, and iconic restaurants are just a short walk away.',
  },
  {
    id: 2,
    title: 'Beachfront Villa',
    type: 'Villa',
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    price: 250,
    category: 'Luxury',
    location: 'Miami',
    image: 'https://th.bing.com/th/id/R.5a7af7ca54fcef640345d9f313641eed?rik=J7gN9bb5lv96DQ&pid=ImgRaw&r=0',
    description:
      'A charming and cozy apartment located in the bustling heart of New York City. This fully furnished apartment features a modern interior design, complete with a well-equipped kitchen, comfortable living space, and breathtaking views of the city skyline. It’s perfect for a family or a small group of friends looking to explore the Big Apple. Attractions such as Central Park, Times Square, and iconic restaurants are just a short walk away.',
  },
  {
    id: 3,
    title: 'Mountain Cabin',
    type: 'Cabin',
    guests: 5,
    bedrooms: 3,
    bathrooms: 2,
    price: 180,
    category: 'Cabins',
    location: 'Denver',
    image: 'https://th.bing.com/th/id/OIP.Rv5BkyJ19WG-LIaiWyzujgHaE8?w=301&h=200&c=7&r=0&o=5&pid=1.7',
    description:
      'A charming and cozy apartment located in the bustling heart of New York City. This fully furnished apartment features a modern interior design, complete with a well-equipped kitchen, comfortable living space, and breathtaking views of the city skyline. It’s perfect for a family or a small group of friends looking to explore the Big Apple. Attractions such as Central Park, Times Square, and iconic restaurants are just a short walk away.',
  },
  {
    id: 4,
    title: 'Luxury Penthouse',
    type: 'Penthouse',
    guests: 8,
    bedrooms: 4,
    bathrooms: 3,
    price: 500,
    category: 'Cabins',
    location: 'Los Angeles',
    image: 'https://th.bing.com/th/id/OIP.Rv5BkyJ19WG-LIaiWyzujgHaE8?w=301&h=200&c=7&r=0&o=5&pid=1.7',
    description:
      'A charming and cozy apartment located in the bustling heart of New York City. This fully furnished apartment features a modern interior design, complete with a well-equipped kitchen, comfortable living space, and breathtaking views of the city skyline. It’s perfect for a family or a small group of friends looking to explore the Big Apple. Attractions such as Central Park, Times Square, and iconic restaurants are just a short walk away.',
  },
  {
    id: 5,
    title: 'Seaside Cottage',
    type: 'Cottage',
    guests: 3,
    bedrooms: 2,
    bathrooms: 1,
    price: 150,
    category: 'Cabins',
    location: 'Malibu',
    image: 'https://th.bing.com/th/id/OIP.Rv5BkyJ19WG-LIaiWyzujgHaE8?w=301&h=200&c=7&r=0&o=5&pid=1.7',
    description:
      'A charming and cozy apartment located in the bustling heart of New York City. This fully furnished apartment features a modern interior design, complete with a well-equipped kitchen, comfortable living space, and breathtaking views of the city skyline. It’s perfect for a family or a small group of friends looking to explore the Big Apple. Attractions such as Central Park, Times Square, and iconic restaurants are just a short walk away.',
  },
  {
    id: 6,
    title: 'Urban Loft',
    type: 'Loft',
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    price: 120,
    category: 'Trending',
    location: 'San Francisco',
    image: 'https://th.bing.com/th/id/OIP.Rv5BkyJ19WG-LIaiWyzujgHaE8?w=301&h=200&c=7&r=0&o=5&pid=1.7',
    description:
      'A charming and cozy apartment located in the bustling heart of New York City. This fully furnished apartment features a modern interior design, complete with a well-equipped kitchen, comfortable living space, and breathtaking views of the city skyline. It’s perfect for a family or a small group of friends looking to explore the Big Apple. Attractions such as Central Park, Times Square, and iconic restaurants are just a short walk away.',
  },
  {
    id: 7,
    title: 'Modern Studio',
    type: 'Studio',
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    price: 90,
    category: 'Trending',
    location: 'Chicago',
    image: 'https://th.bing.com/th/id/OIP.Rv5BkyJ19WG-LIaiWyzujgHaE8?w=301&h=200&c=7&r=0&o=5&pid=1.7',
    description:
      'A charming and cozy apartment located in the bustling heart of New York City. This fully furnished apartment features a modern interior design, complete with a well-equipped kitchen, comfortable living space, and breathtaking views of the city skyline. It’s perfect for a family or a small group of friends looking to explore the Big Apple. Attractions such as Central Park, Times Square, and iconic restaurants are just a short walk away.',
  },
  {
    id: 8,
    title: 'Rustic Barn',
    type: 'Barn',
    guests: 10,
    bedrooms: 5,
    bathrooms: 3,
    price: 350,
    category: 'Trending',
    location: 'Nashville',
    image: 'https://th.bing.com/th/id/OIP.Rv5BkyJ19WG-LIaiWyzujgHaE8?w=301&h=200&c=7&r=0&o=5&pid=1.7',
    description:
      'A charming and cozy apartment located in the bustling heart of New York City. This fully furnished apartment features a modern interior design, complete with a well-equipped kitchen, comfortable living space, and breathtaking views of the city skyline. It’s perfect for a family or a small group of friends looking to explore the Big Apple. Attractions such as Central Park, Times Square, and iconic restaurants are just a short walk away.',
  },
  {
    id: 9,
    title: 'Coastal Mansion',
    type: 'Mansion',
    guests: 12,
    bedrooms: 6,
    bathrooms: 4,
    price: 800,
    category: 'Unique Stays',
    location: 'Hamptons',
    image: 'https://th.bing.com/th/id/OIP.Rv5BkyJ19WG-LIaiWyzujgHaE8?w=301&h=200&c=7&r=0&o=5&pid=1.7',
    description:
      'A charming and cozy apartment located in the bustling heart of New York City. This fully furnished apartment features a modern interior design, complete with a well-equipped kitchen, comfortable living space, and breathtaking views of the city skyline. It’s perfect for a family or a small group of friends looking to explore the Big Apple. Attractions such as Central Park, Times Square, and iconic restaurants are just a short walk away.',
  },
  {
    id: 10,
    title: 'Countryside Farmhouse',
    type: 'Farmhouse',
    guests: 8,
    bedrooms: 4,
    bathrooms: 2,
    price: 250,
    category: 'Unique Stays',
    location: 'Texas Hill Country',
    image: 'https://th.bing.com/th/id/OIP.Rv5BkyJ19WG-LIaiWyzujgHaE8?w=301&h=200&c=7&r=0&o=5&pid=1.7',
    description:
      'A charming and cozy apartment located in the bustling heart of New York City. This fully furnished apartment features a modern interior design, complete with a well-equipped kitchen, comfortable living space, and breathtaking views of the city skyline. It’s perfect for a family or a small group of friends looking to explore the Big Apple. Attractions such as Central Park, Times Square, and iconic restaurants are just a short walk away.',
  },
];

module.exports = listings;
